[ensemble]
    ne = 10
    natural_gradient = false
    [ensemble.controls]
        rate_inj1 = {mean='initrates.npz', std='5%', limits=[0, 500]}
        rate_inj2 = {mean='initrates.npz', std='5%', limits=[0, 500]}
        rate_inj3 = {mean='initrates.npz', std='5%', limits=[0, 500]}
        rate_inj4 = {mean='initrates.npz', std='5%', limits=[0, 500]}

[optim]
    transform = true
    maxiter = 10
    step_size_adapt = 2
    savefolder = 'Results'
    saveit = true

[simulator]
    parallel = 5
    runfile  = '5SPOT'
    datatype = ['FOPT', 'FGPT', 'FWPT', 'FWIT']
    reporttype = 'dates'

    [simulator.reportpoint]
        start = '2000-02-01'
        end = '2008-01-01'
        freq = 'MS'

    [simulator.npv_const]
        wop = 400
        wgp = 0.4
        wwp = 20
        wwi = 10
        disc = 0.08
        obj_scaling = -1.0e9
